CREATE TABLE users (
	username TEXT NOT NULL PRIMARY KEY,
	password TEXT NOT NULL,
	avatar TEXT NOT NULL DEFAULT '/static/avatar.png',
	follows TEXT NOT NULL DEFAULT '[]'
);

CREATE TABLE posts (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	author TEXT NOT NULL,
	content TEXT NOT NULL,
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);